spring:
  application:
    name: oidc-minimal
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github_client_id}
            client-secret: ${github_client_secret}
            scope:
              - user
            authorization-grant-type: authorization_code
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            scope: https://www.googleapis.com/auth/userinfo.email
            authorization-grant-type: authorization_code
  main:
    banner-mode: off
logging:
  level:
    eu: WARN
    org: WARN
    com: WARN